name: release

on:
  release: # Docs: <https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release>
    types: [published]

jobs:
  godocs:
    name: Renew docs and cache (${{ matrix.proxy }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        proxy:
          - https://proxy.golang.org
          - https://goproxy.cn
          - https://goproxy.dev
    steps:
      - uses: actions/setup-go@v3

      - uses: gacts/github-slug@v1
        id: slug

      - name: Get the module using proxy
        env: {GOPROXY: '${{ matrix.proxy }}'}
        run: |
          go mod init foo
          go get -v -x -u "github.com/tarampampam/urfave-cli-docs@${{ steps.slug.outputs.tag-name }}"
